name: Test
"on":
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP_VERSION:
          - 7.3
          - 7.4
          - 8.0
    container:
      image: "php:${{ matrix.PHP_VERSION }}"
    steps:  
    - name: Download latest git
      run: "add-apt-repository ppa:git-core/ppa && apt-get update && apt-get install -y git unzip"
    - name: Download composer
      run: "cd $(mktemp -d) && curl https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
    - name: Install deps
      run: "composer install"
    - uses: actions/checkout@v2
    - name: Tests
      run:  ./vendor/bin/phpunit
